### ISSUE TITLE
Front-end – TICKET

### ISSUE THREAD

**Issue by juizmill** [juizmill/ListService#49]

**Comment by meccajordao** [comment]
O modelo do ticket ficou bom...esta aprovada!
![Ticket](https://f.cloud.github.com/assets/2580374/158973/a649c958-76fc-11e2-858c-d7e235eb3537.jpg)

**Comment by juizmill** [comment]
Confirma se temos que mudar mais alguma coiza.
![Ticket](https://f.cloud.github.com/assets/1959742/164245/784e814c-7887-11e2-9e6e-efd752ac5c1d.jpg)
