### ISSUE TITLE
Front-end HOME

### ISSUE THREAD

**Issue by juizmill** [juizmill/ListService#55]
Quando a pessoa fazer o login a primeira tela tem que ser a home.

**Comment by juizmill** [comment]
Confirma se temos que mudar mais alguma coiza.
![Home](https://f.cloud.github.com/assets/1959742/164248/06751026-7888-11e2-92af-cc254f5875c2.jpg)

**Comment by juizmill** [comment]
Andre da uma olhada de como ficou eu achei mais interessante este segundo exemplo, ele já está rodando. Me diz o que vc acha.
![Screen Shot 2013-02-17 at 19 17 38](https://f.cloud.github.com/assets/1959742/165600/631d2b6c-7958-11e2-94bf-8a1b15f62e9e.png)

**Comment by meccajordao** [comment]
Jesus ficou muito bom cara.. o sistema esta ficando fera demais...

**Comment by juizmill** [comment]
Ficou um pouco diferente a cor da caixas e dos botões, acho que deve ser uma pequena diferença do Programa que uso para criar os protótipos.
