### ISSUE TITLE
Logotipo Sistema

### ISSUE THREAD

**Issue by meccajordao** [juizmill/ListService#72]

**Comment by meccajordao** [comment]
Juiz.. Fiz um modelo do logotipo do sistema o que você acha.. da uma olhada ai e me diz..
![logo sistema 2](https://f.cloud.github.com/assets/2580374/158976/e00abbfc-76fc-11e2-92f4-4b41253ed494.jpg)

**Comment by juizmill** [comment]
Ficou muito bom! Gostei! 

Vou colocar ele no protótipo para ter uma ideia.

**Comment by juizmill** [comment]
Hehe sem querer eu fechei esta Issue

**Comment by juizmill** [comment]
A logo está no formato JPG envia uma no formato PNG
