### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by juizmill** [juizmill/ListService#84]
Criar os teste de cada módulo.

**Comment by juizmill** [comment]
Irei fazer as configurações necessárias.

**Comment by juizmill** [comment]
Vou fazer os testes baseado no curso da School of Net, tem algum problema?

**Comment by danizord** [comment]
@juizmill eu não sei como é o curso da School of Net =/

**Comment by juizmill** [comment]
@danizord Vc sabe onde eu possa me basear para criar as configurações necessárias?

**Comment by danizord** [comment]
@juizmill vou mandar uma sugestão.

**Comment by juizmill** [comment]
O que podemos testar, controller, entity, fixtire e service de cada módulo, o que vocês me diz?

**Comment by ghost** [comment]
Os testes já foram iniciados?

**Comment by juizmill** [comment]
Tem um exemplo de configuração que fiz e enviei neste semana, mas por hora não tem nada definido ainda.

**Comment by ghost** [comment]
Continuarei os testes

**Comment by juizmill** [comment]
@ghean vc vai fazer os testes para depois dar continuidade no projeto, "refatorar", qual a sua dica

**Comment by danizord** [comment]
Eu sugiro que os testes sejam feitos junto com a refatoração (criar testes para código novo). Criar testes para o código atual é desnecessário.

**Comment by ghost** [comment]
Atravéz dos testes é que podemos refatorar com segurança e qualidade, refatoração faz parte do ciclo de testes.
Para se evoluir com segurança e qualidade o código atual precisa estar testado. mas nada impede de alguém ir adicionado novas funcionalidades e os testes virem em seguida, não é o ideal, mas nada impede disso acontecer.

**Comment by juizmill** [comment]
Só para reforçar as funcionalidades do sistema: cadastro de Empresa (NOVO),  Funcionário, clientes da Empresa e Solicitações de serviços (ticket)

**Comment by danizord** [comment]
@ghean Sim, o ideal seria que as novas funcionalidades sejam adicionadas já testadas. Só acho desnecessário criar testes para esse código atual, porque a maior parte desse código é _intestável_ e está obsoleto. Por isso, na minha opinião, o ideal seria criar os testes já pensando na refatoração.

**Comment by ghost** [comment]
Isso mesmo @danizord , mas para refatorar com segurança preciso do testes. mesmo estando obsoleto, é os teste que irá me guiar para melhorar/refatorar os códigos.

**Comment by danizord** [comment]
@ghean Show, vamo q vamo :D

**Comment by juizmill** [comment]
O que virou dos testes?

**Comment by juizmill** [comment]
Olá eu fiz uma arquitetura de TDD e está no módulo LSUser, não sei se é a melhor forma de trabalhar com TDD no ZF2 e venho pedir a colaboração de todos para saber se devo continuar desta forma ou se alguém tiver uma nova sugestão que envie para ser avaliada.

**Comment by danizord** [comment]
@juizmill, se não for muito inconveniente pra vc, seria interessante vc não comitar direto na branch master, mas fazer uma pull-request, assim fica mais fácil analisar e dar um feedback no código.

Btw, vou dar uma olhada nos testes do LSUser e ver se posso colaborar com alguma ideia.

**Comment by juizmill** [comment]
@danizord, valeu pela dica! Em relação aos testes, é viável testar os formulários e seus filtros? Qual classes seria interessante realizar os testes, <strong> controller, form,  form filter, services, entity </strong>?

Sempre tenho estas dúvidas e gostaria muito da dica de vocês.

**Comment by danizord** [comment]
IMHO, todas as classes da aplicação devem ser testadas.

**Comment by juizmill** [comment]
Olá!
Fiz uma configuração para rodar os testes, está no módulo <b>LSPriority</b> que se encontra no branch  <b><a href="https://github.com/juizmill/ListService/tree/development">development</a></b> por enquanto só fiz os testes na <b>Entity</b> e <b>Repository</b> e gostaria da opinião de vocês se devo ou não prosseguir com esta configuração..

**Comment by juizmill** [comment]
Nenhuma opinião?

**Comment by juizmill** [comment]
Em relação a qual classe que deve ser testada, eu acho que deveria ser as seguinte:
<b>Entity</b>, <b>Service</b>, e classes do próprio projeto.

Removendo dos testes o <b>controller</b> e <b>fixtures</b>, uma vez sabendo que estas classes já foram testadas..
