### ISSUE TITLE
Problemas para atualizar os pacote

### ISSUE THREAD

**Issue by juizmill** [juizmill/ListService#85]
Eu atualizei os pacotes e baixou a versão 2.2.0rc3 do Zend, e parou de funcionar o sistema, gostaria de saber se alguém está tendo problemas?

**Comment by gilcierweb** [comment]
Olá estou com o mesmo problema dar o erro 500 como se tivesse faltando alguma coisa, algum arquivo.
alguem saber o que pode ser.??

**Comment by juizmill** [comment]
mudei a versão do ZF2 para 2.*@stable e está instalando normal. para evitar erro de TimeOut usa este comando:
COMPOSER_PROCESS_TIMEOUT=9000 php composer.phar install
ou
COMPOSER_PROCESS_TIMEOUT=9000 php composer.phar update

**Comment by gilcierweb** [comment]
cara eu clonei novamente o projeto em ambiente ubuntu instalo todas as dependências mais continua com o erro 500. não sei o pode ser, o composer baixou todas as dependências e o erro persiste.

**Comment by juizmill** [comment]
Deve ter acontecido algum problema, abre uma ISSUE relatando o erro para correção.
