### ISSUE TITLE
Erro 500 após baixar dependências pelo composer

### ISSUE THREAD

**Issue by gilcierweb** [juizmill/ListService#88]
Eu clonei o projeto e baixei as dependências do projeto pelo composer, ele baixa todas elas, mais quando coloco pra rodar dar sempre o erro 500 como se tivesse faltando alguma coisa.

**Comment by danizord** [comment]
Vc está usando Apache? Pode postar o conteúdo que está sendo gerado no error log?

**Comment by gilcierweb** [comment]
Estou usando apache.
o log de erro é esse.
[Mon Jan 06 08:07:38 2014] [error] [client 127.0.0.1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://dev.gilcierweb2/
[Mon Jan 06 08:07:43 2014] [error] [client 127.0.0.1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

**Comment by danizord** [comment]
Hmm, loop infinito. Provavelmente algo relacionado a autenticação. Vou ver se consigo simular o erro na minha máquina hoje a noite. @juizmill vc está tendo esse problema?

**Comment by juizmill** [comment]
O meu aqui está tudo parado pq estou mexendo com as estruturas de pastas e
arquivos junto com o @ghean

**Comment by juizmill** [comment]
Acabo de realizar um teste, baixei o repositório a partir da versão <a href="https://github.com/juizmill/ListService/archive/V0.01.zip">v0.01</a> e executei os comandos necessários e rodou normal, o único problema era que eu estava usando uma porta por exemplo 8080 e redirecionava para uma página inválida, fui até o index.php que está na pasta public e alterei este IF:

<pre>
$host = $_SERVER['REQUEST_URI'];
if ($host == '/' || $host == '') {
    header('Location: http://'.$_SERVER['SERVER_NAME'].':'.$_SERVER['SERVER_PORT'].'/auth');
    exit();
} 
</pre>

e pronto tudo funcionou normal.

**Comment by gilcierweb** [comment]
Clonei novamente o projeto mais continua o erro vejo os prints.
![captura de tela de 2014-01-07 13 35 18](https://f.cloud.github.com/assets/1915433/1860864/c1615cd8-77b9-11e3-93e7-03e607f7f1b3.png)

![captura de tela de 2014-01-07 13 27 11](https://f.cloud.github.com/assets/1915433/1860831/5a8a30fc-77b9-11e3-8390-fbf062808e4e.png)
![captura de tela de 2014-01-07 13 26 35](https://f.cloud.github.com/assets/1915433/1860833/602c87bc-77b9-11e3-802f-ceb90c69cd83.png)
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/interbase.ini on line 1 in Unknown on line 0
Loading composer repositories with package information
Installing dependencies (including require-dev)
file_put_contents(/home/gilcierweb/.composer/cache/repo/https---packagist.org/provider-symfony$yaml.json): failed to open stream: Permission denied
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
- Installing zendframework/zendframework (2.2.5)
  Loading from cache
  
  Skipped installation of bin/classmap_generator.php for package zendframework/zendframework: name conflicts with an existing file
  Skipped installation of bin/pluginmap_generator.php for package zendframework/zendframework: name conflicts with an existing file
  Skipped installation of bin/templatemap_generator.php for package zendframework/zendframework: name conflicts with an existing file
- Installing doctrine/lexer (dev-master f12a5f7)
  Cloning f12a5f74e5f4a9e3f558f3288504e121edfad891
- Installing doctrine/annotations (dev-master a11349d)
  Cloning a11349d39d85bef75a71bd69bd604ac4fb993f03
- Installing doctrine/collections (dev-master e6d8f12)
  Cloning e6d8f1240e10f268c8e8c30e9e88a12853f84695
- Installing doctrine/cache (dev-master 36c4eee)
  Cloning 36c4eee5051629524389da376ba270f15765e49f
- Installing doctrine/inflector (dev-master a81c334)
  Cloning a81c334f2764b09e2f13a55cfd8fe3233946f728
- Installing doctrine/common (2.4.x-dev c94d6ff)
  Cloning c94d6ff79e25418b1225e187c782bf4742f23a8b
- Installing doctrine/dbal (2.4.x-dev 6f4294c)
  Cloning 6f4294c3decd014627076982d99d626f5a3b1012
- Installing symfony/console (dev-master 0afe517)
  Cloning 0afe517faecb1d3b397a0297d3f7d2cc39587230
- Installing doctrine/orm (2.4.x-dev 9486867)
  Cloning 948686727982cc94d180b5f65b2c8641a818efd2
  
  Skipped installation of bin/doctrine for package doctrine/orm: name conflicts with an existing file
  Skipped installation of bin/doctrine.php for package doctrine/orm: name conflicts with an existing file
- Installing doctrine/doctrine-module (dev-master dba2f4a)
  Cloning dba2f4a4807e28b6b52eeab26da897bfdf9e3c92
  
  Skipped installation of bin/doctrine-module for package doctrine/doctrine-module: name conflicts with an existing file
- Installing doctrine/doctrine-orm-module (dev-master 7dcbaf0)
  Cloning 7dcbaf04ef01895a64a9ab61b00970ca52f261db
- Installing doctrine/data-fixtures (dev-master 4a81be0)
  Cloning 4a81be009d8437326acfcdd68888d1c5b8e2fb40
- Installing hounddog/doctrine-data-fixture-module (dev-master 6beeb4f)
  Cloning 6beeb4fb09bdd4adb49a242cfd31589981fc4e6f
- Installing zendframework/zend-developer-tools (dev-master 9a88486)
  Cloning 9a8848612c0c6d9890dd6533b3dd5045745e1299
- Installing phpunit/php-timer (dev-master 19689d4)
  Cloning 19689d4354b295ee3d8c54b4f42c3efb69cbc17c
- Installing symfony/yaml (dev-master c2e0657)
  Cloning c2e065720708d6db30dfba1278b8f53c45dd9fe0
- Installing phpunit/php-text-template (dev-master 1eeef10)
  Cloning 1eeef106193d2f8c539728e566bb4793071a9e18
- Installing phpunit/phpunit-mock-objects (1.2.x-dev 3e40f3b)
  Cloning 3e40f3b3f18c044a24688fe406440d7fd537744a
- Installing phpunit/php-token-stream (dev-master 292f4d5)
  Cloning 292f4d5772dad5a12775be69f4a8dd663b20f103
- Installing phpunit/php-file-iterator (dev-master acd6903)
  Cloning acd690379117b042d1c8af1fafd61bde001bf6bb
- Installing phpunit/php-code-coverage (1.2.x-dev 10c5b2c)
  Cloning 10c5b2c8b72a801eaad0031cd6a6a3686909c5a9
- Installing phpunit/phpunit (3.7.x-dev 92e8faf)
  Cloning 92e8faf88773fa173b0ab2425ba4ade434c58c5d
  
  Skipped installation of composer/bin/phpunit for package phpunit/phpunit: name conflicts with an existing file
- Installing gedmo/doctrine-extensions (dev-master 20d0d03)
  Cloning 20d0d03e79dc5e527c97ae5de35e03bde1984bc7

zendframework/zendframework suggests installing ext-intl (ext/intl for i18n features (included in default builds of PHP))
zendframework/zendframework suggests installing ircmaxell/random-lib (Fallback random byte generator for Zend\Math\Rand if OpenSSL/Mcrypt extensions are unavailable)
zendframework/zendframework suggests installing ocramius/proxy-manager (ProxyManager to handle lazy initialization of services)
zendframework/zendframework suggests installing zendframework/zendpdf (ZendPdf for creating PDF representations of barcodes)
zendframework/zendframework suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha for rendering ReCaptchas in Zend\Captcha and/or Zend\Form)
symfony/console suggests installing symfony/event-dispatcher ()
doctrine/doctrine-orm-module suggests installing doctrine/migrations (doctrine migrations if you want to keep your schema definitions versioned)
doctrine/data-fixtures suggests installing doctrine/mongodb-odm (For loading MongoDB ODM fixtures)
doctrine/data-fixtures suggests installing doctrine/phpcr-odm (For loading PHPCR ODM fixtures)
zendframework/zend-developer-tools suggests installing bjyoungblood/bjy-profiler (Version: dev-master, allows the usage of the (Zend) Db collector.)
zendframework/zend-developer-tools suggests installing ocramius/ocra-service-manager (OcraServiceManager can help you track dependencies within your application.)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (>=1.1.0,<1.2.0)
gedmo/doctrine-extensions suggests installing doctrine/mongodb-odm (>=1.0.0-BETA7)
gedmo/doctrine-extensions suggests installing doctrine/mongodb (>=1.0.1)
Writing lock file
Generating autoload files

**Comment by juizmill** [comment]
Usa <strong>Virtual Hosts</strong>, e usa o seguinte comando para atualizar a APP,

<pre>
sudo COMPOSER_PROCESS_TIMEOUT=9000 php composer.phar update
</pre>

Instala também o <strong>INTL</strong> com este comando no terminal:

<pre>
sudo apt-get install php5-intl
</pre>

Seu maior problema é que vc não tem permissão na pasta ListService, e não está utilizando Virtual Hosts, executando os comando acima e habilitar o Virtual Hosts já ficará tudo OK.

**Comment by gilcierweb** [comment]
Fiz o que você disse deu certo criei uma virtual host especifica e instalei php5-intl.
mostra  essa tela http://dev.listservice/auth 
![captura de tela de 2014-01-09 13 31 01](https://f.cloud.github.com/assets/1915433/1879568/07eb117e-794c-11e3-8d29-2e45418ed713.png)
abro o arquivo do banco de dados no workbench e exporto o sql mais tem alguns campos que não tem tipo e dar um erro na hora de criar as tabelas..

**Comment by juizmill** [comment]
Remove todas as tabelas da base de dados, depois cria ela com o próprio Doctrine, fiz uma vídeo aula mostrando como vc pode ver a lista de comandos do Doctrine e algumas funcionalidades, http://blog.webpatterns.com.br/cursos/zend-framework/mapeando-tabela-post-doctrine-orm/, depois de criadas executa as FIXTURE para popular o banco de dados com alguns dados de teste.
