### ISSUE TITLE
Dificuldade para iniciar no projeto

### ISSUE THREAD

**Issue by werepa** [juizmill/ListService#89]
Segui os passos citados nos posts, mas continuo recebendo o erro:

[Tue Jan 28 08:57:48 2014] [error] [client 127.0.0.1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInterna$

**\* Para o endereço: http://listservice/auth

Executar as FIXTURE seria o comando abaixo?

./doctrine-module data-fixture:import;

Preciso de ajuda para estes ajustes de configuração...

**Comment by juizmill** [comment]
o comando é este mesmo!

Em 28 de janeiro de 2014 08:04, werepa notifications@github.com escreveu:

> Segui os passos citados nos posts, mas continuo recebendo o erro:
> 
> [Tue Jan 28 08:57:48 2014] [error] [client 127.0.0.1] Request exceeded the
> limit of 10 internal redirects due to probable configuration error. Use
> 'LimitInterna$
> 
> **\* Para o endereço: http://listservice/auth
> 
> Executar as FIXTURE seria o comando abaixo?
> 
> ./doctrine-module data-fixture:import;
> 
> Preciso de ajuda para estes ajustes de configuração...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/juizmill/ListService/issues/89
> .

## 

_JESUS VIEIRA_
_Programador back-end_
_Web Patterns - Desenvolvimento de Web Sites_
_http://webpatterns.com.br http://webpatterns.com.br_
_http://blog.webpatterns.com.br http://blog.webpatterns.com.br/_

**Comment by werepa** [comment]
Eu já havia executado o comando, mas não percebi nenhuma modificação nas tabelas... continuam todas vazias. E ao acessar o endereço do virtualhost: http://listservice recebo a mensagem de erro acima descrita. Uso o Apache em um MacBook com OSX 10.9.1

O que você sugere para que eu possa solucionar este erro e começar a navegar pelo projeto?

**Comment by werepa** [comment]
O problema foi resolvido: basta mover o arquivo .htaccess para o diretório public
