### ISSUE TITLE
Formulários

### ISSUE THREAD

**Issue by juizmill** [juizmill/ListService#90]
O que vocês acham de trabalhar com Zend\Form\Annotation?

**Comment by danizord** [comment]
Eu particularmente não gosto de usar annotations para esse fim. Especialmente pq na maioria casos as propriedades das entidades não são exatamente iguais aos elementos do form. Por exemplo, o input "submit". Vc terá que adicionar uma propriedade "submit" na sua entity só pra fazer funcionar as annotations :D

Se a intenção é remover as classes que estendem o `Zend\Form`, eu sugiro usar a [Zend\Form\FormAbstractServiceFactory](http://framework.zend.com/manual/2.3/en/modules/zend.mvc.services.html#zend-form-formabstractservicefactory).

**Comment by juizmill** [comment]
@danizord mas você pode usar um recurso no module.php com o método <strong>getFormElementConfig()</strong>,  com este método vc pode ADD funcionalidades em seu formulário ai não tem a necessidade de criar  uma propriedade em sua <strong>Entity</strong> para o <strong>Submit</strong>.

**Comment by danizord** [comment]
@juizmill Sim, mas ae vc vai ter que criar uma factory pra cada form de qualquer forma. Por isso eu acho mais adequado usar a `FormAbstractServiceFactory`.

**Comment by juizmill** [comment]
Tem algum exemplo deste _FormAbstractServiceFactory_

Em 24 de março de 2014 12:46, Daniel Gimenes notifications@github.comescreveu:

> @juizmill https://github.com/juizmill Sim, mas ae vc vai ter que criar
> uma factory pra cada form de qualquer forma. Por isso eu acho mais adequado
> usar a FormAbstractServiceFactory.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/juizmill/ListService/issues/90#issuecomment-38468558
> .

## 

_JESUS VIEIRA_
_Programador back-end_
_Web Patterns - Desenvolvimento de Web Sites_
_http://webpatterns.com.br http://webpatterns.com.br_
_http://blog.webpatterns.com.br http://blog.webpatterns.com.br/_

**Comment by danizord** [comment]
@juizmill No link do meu comentário tem um exemplo. (:

**Comment by juizmill** [comment]
Usando annotation eu acho que seria um ganho, pq teria que criar menas classes, e aumentando a produtividade. A única coisa que deve ser feita é criar um Service para a criação do Form.
